export interface IProfileAvatar {
    accessory: String,
    body: String,
    clothing: String,
    clothingColor: String,
    eyebrows: String,
    eyes: String,
    facialHair: String,
    graphic: String,
    hair: String,
    hairColor: String,
    hat: String,
    hatColor: String,
    lashes: Boolean,
    lipColor: String,
    mask: Boolean,
    mouth: String,
    skinTone: String,
}
